version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: PigeonSkyRaceSecurity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./PigeonSkyRaceApi
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PigeonSkyRaceSecurity
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./PigeonSkyRaceFront
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data: