spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PigeonSkyRaceSecurity
    username: postgres
    password: 0074
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect